# database configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nft?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=America/New_York
    username: root
    password: 123456
    schema: classpath:nft.sql
    initialization-mode: always

# log configuration
mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml